In [ ]:
import pandas as pd
value_n_list=["andrew","philip","jhon","juan"]
print(value_n_list)

value_w_list=[50, 78, 91.5,80]
value_h_list=[1.76,1.87, 1.69,1.73]

data_dict={"name":value_n_list,
           "weight":value_w_list,
           "height":value_h_list}

print(data_dict)

df=pd.DataFrame(data_dict)

print(df)


df

['andrew', 'philip', 'jhon', 'juan']
{'name': ['andrew', 'philip', 'jhon', 'juan'], 'weight': [50, 78, 91.5, 80], 'height': [1.76, 1.87, 1.69, 1.73]}
     name  weight  height
0  andrew    50.0    1.76
1  philip    78.0    1.87
2    jhon    91.5    1.69
3    juan    80.0    1.73

     name  weight  height
0  andrew    50.0    1.76
1  philip    78.0    1.87
2    jhon    91.5    1.69
3    juan    80.0    1.73

In [ ]:
df["bmi"] =  df["weight"] / (df["height"]** 2)
df

     name  weight  height        bmi
0  andrew    50.0    1.76  16.141529
1  philip    78.0    1.87  22.305471
2    jhon    91.5    1.69  32.036693
3    juan    80.0    1.73  26.729927

In [ ]:
s=50+78+91.5

In [ ]:
n=3
p=s/3
p

73.16666666666667

In [ ]:
df.describe(include="all")

          name     weight   height        bmi
count        4   4.000000  4.00000   4.000000
unique       4        NaN      NaN        NaN
top     andrew        NaN      NaN        NaN
freq         1        NaN      NaN        NaN
mean       NaN  74.875000  1.76250  24.303405
std        NaN  17.618054  0.07719   6.740418
min        NaN  50.000000  1.69000  16.141529
25%        NaN  71.000000  1.72000  20.764485
50%        NaN  79.000000  1.74500  24.517699
75%        NaN  82.875000  1.78750  28.056619
max        NaN  91.500000  1.87000  32.036693

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   weight  4 non-null      float64
 2   height  4 non-null      float64
 3   bmi     4 non-null      float64
dtypes: float64(3), object(1)
memory usage: 260.0+ bytes

In [ ]:
df.shape

(4, 4)

In [ ]:
df.describe()

          weight   height        bmi
count   4.000000  4.00000   4.000000
mean   74.875000  1.76250  24.303405
std    17.618054  0.07719   6.740418
min    50.000000  1.69000  16.141529
25%    71.000000  1.72000  20.764485
50%    79.000000  1.74500  24.517699
75%    82.875000  1.78750  28.056619
max    91.500000  1.87000  32.036693

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
weight,4.0,74.875000,17.618054,50.000000,71.000000,79.000000,82.875000,91.500000
height,4.0,1.762500,0.077190,1.690000,1.720000,1.745000,1.787500,1.870000
bmi,4.0,24.303405,6.740418,16.141529,20.764485,24.517699,28.056619,32.036693

In [ ]:
df["bmi"] =  df["weight"] / (df["height"]** 2)

In [ ]:
df.describe(include="O")

          name
count        4
unique       4
top     andrew
freq         1

In [ ]:
v = ((50-p)**2 + (78-p)**2 + (91.5-p)**2