In [1]:
import pandas as pd
from io import StringIO
from sklearn.linear_model import LinearRegression
import numpy as np

In [6]:
# Data provided by the user
data = """Y	X1	X2	X3	X4
78,5	7	26	6	60
74,3	1	29	15	52
104,3	11	56	8	20
87,6	11	31	8	47
95,9	7	52	6	33
109,2	11	55	9	22
102,7	3	71	17	6
72,5	1	31	22	44
93,1	2	54	18	22
115,9	21	47	4	26
83,8	1	40	23	34
113,3	11	66	9	12
109,4	10	68	8	12"""

# Read the data into a pandas DataFrame, replacing comma with dot for decimals
df = pd.read_csv(StringIO(data), sep='\t').replace(',', '.', regex=True)

# Convert all columns to numeric type
for col in df.columns:
    df[col] = pd.to_numeric(df[col])

display(df.head())

       Y  X1  X2  X3  X4
0   78.5   7  26   6  60
1   74.3   1  29  15  52
2  104.3  11  56   8  20
3   87.6  11  31   8  47
4   95.9   7  52   6  33

In [7]:
# Define dependent variable (Y) and independent variables (X)
X = df[['X1', 'X2', 'X3', 'X4']]
Y = df['Y']

# Initialize and fit the Linear Regression model
model = LinearRegression()
model.fit(X, Y)

# Display the results
print(f"Coefficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")

Coefficients: [ 1.55110265  0.51016758  0.1019094  -0.14406103]
Intercept: 62.4053692999176

The regression equation is of the form:
$Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \beta_4 X_4$

Where:
- $\beta_0$ is the intercept.
- $\beta_i$ are the coefficients for each independent variable $X_i$.

From the results:
- The intercept ($\beta_0$) is approximately `{:.2f}`.
- The coefficients ($\beta_1, \beta_2, \beta_3, \beta_4$) are approximately `{:.2f}, {:.2f}, {:.2f}, {:.2f}` respectively.

This means for every one-unit increase in $X_1$, $Y$ increases by `{:.2f}` (holding other variables constant), and similarly for other variables. The intercept is the predicted value of $Y$ when all $X$ variables are zero.

In [8]:
md_code = f"""The regression equation is of the form:
$Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \beta_4 X_4$

Where:
- $\beta_0$ is the intercept.
- $\beta_i$ are the coefficients for each independent variable $X_i$.

From the results:
- The intercept ($\beta_0$) is approximately {model.intercept_:.2f}.
- The coefficients ($\beta_1, \beta_2, \beta_3, \beta_4$) are approximately {model.coef_[0]:.2f}, {model.coef_[1]:.2f}, {model.coef_[2]:.2f}, {model.coef_[3]:.2f} respectively.

This means for every one-unit increase in $X_1$, $Y$ increases by {model.coef_[0]:.2f} (holding other variables constant), and similarly for other variables. The intercept is the predicted value of $Y$ when all $X$ variables are zero."""

from IPython.display import display, Markdown
display(Markdown(md_code))

The regression equation is of the form:
$Y = eta_0 + eta_1 X_1 + eta_2 X_2 + eta_3 X_3 + eta_4 X_4$

Where:
- $eta_0$ is the intercept.
- $eta_i$ are the coefficients for each independent variable $X_i$.

From the results:
- The intercept ($eta_0$) is approximately 62.41.
- The coefficients ($eta_1, eta_2, eta_3, eta_4$) are approximately 1.55, 0.51, 0.10, -0.14 respectively.

This means for every one-unit increase in $X_1$, $Y$ increases by 1.55 (holding other variables constant), and similarly for other variables. The intercept is the predicted value of $Y$ when all $X$ variables are zero.

In [5]:
df

        Y  X1  X2  X3   X4
0    78.5   7  26   6   60
1    74.3   1  29  15   52
2   104.3  11  56   8   20
3    87.6  11  31   8   47
4    95.9   7  52   6  332
5   109.2  11  55   9   22
6   102.7   3  71  17    6
7    72.5   1  31  22   44
8    93.1   2  54  18   22
9   115.9  21  47   4   26
10   83.8   1  40  23   34
11  113.3  11  66   9   12
12  109.4  10  68   8   12